/**
 * @file export.ts
 * @description Export utilities for Clippy — PDF and Markdown download.
 *
 * OVERVIEW
 * --------
 * After analysis, users can download the results in two formats:
 *   - PDF: a formatted report with all model results, scores, flags, and dimensions
 *   - Markdown: a structured .md file suitable for sharing via Git or email
 *
 * DESIGN DECISIONS
 * ----------------
 *
 * 1. jsPDF vs html2canvas
 *    We use jsPDF's built-in text/table API rather than html2canvas screenshot
 *    because:
 *    a) Screenshots capture screen resolution artifacts (CSS shadows, pixel offsets)
 *    b) jsPDF text is searchable, copy-pasteable, and accessible
 *    c) Smaller file size (typically 50–200KB vs 1–5MB for screenshots)
 *    d) Works offline — no browser paint cycle needed
 *    Trade-off: we lose the exact visual appearance of the UI. This is acceptable
 *    for a report export — content > aesthetics.
 *
 * 2. Markdown via Blob URL
 *    No library needed — we build the Markdown string directly and create a
 *    temporary Blob URL for download. The URL is revoked immediately after
 *    the browser starts the download to prevent memory leaks.
 *
 * 3. All exports are purely client-side
 *    No server roundtrip. The file is constructed entirely in the JS heap
 *    and pushed to the user via a synthetic <a> click. This is consistent
 *    with Clippy's zero-backend architecture.
 *
 * 4. Legal disclaimer
 *    Every export includes a clear disclaimer that results are AI-generated
 *    and not legal advice. This is important both for user clarity and for
 *    Clippy's own legal positioning (AI outputs ≠ legal advice).
 *
 * DEPENDENCIES
 * ------------
 * - jspdf ^4.x (already in package.json)
 * - No html2canvas (not needed — text-based PDF)
 */

import jsPDF from "jspdf";
import type { ModelResult } from "@shared/schema";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * The minimum information needed by the export functions.
 * fileName is shown in the report header; analyzedAt is the timestamp.
 */
export interface ExportContext {
  /** Original filename of the uploaded contract. */
  fileName: string;
  /** ISO timestamp of when the analysis was run. */
  analyzedAt: string;
  /** List of enabled prompt titles (shown in the report as "Objectives"). */
  promptTitles: string[];
  /** Per-model results to include in the export. */
  results: ModelResult[];
}

// ---------------------------------------------------------------------------
// Legal disclaimer text (used in both PDF and Markdown exports)
// ---------------------------------------------------------------------------

/**
 * Standard legal disclaimer appended to all Clippy exports.
 * This is intentionally brief and non-alarmist — it informs without obscuring.
 */
const LEGAL_DISCLAIMER =
  "⚠ AI-generated analysis. Not legal advice. Consult a qualified lawyer before acting on any finding. " +
  "Results may miss clauses, misinterpret context, or reflect outdated legal standards.";

// ---------------------------------------------------------------------------
// PDF export
// ---------------------------------------------------------------------------

/**
 * Generates a PDF report of the Clippy analysis results and triggers a download.
 *
 * REPORT STRUCTURE
 * ----------------
 *   Cover page:
 *     - Clippy logo (yellow rounded rect + navy circles for eyes)
 *     - Title: "Clippy — Contract Analysis Report"
 *     - Subtitle: "clippy.legal — open-source AI contract analyzer"
 *     - Contract metadata: file name, analysis timestamp, models used, objectives
 *
 *   Per-model section (one per result, starting on the same page):
 *     - Model name header (warm cream background)
 *     - Trust score badge (green/yellow/orange/red, top-right)
 *     - Jurisdiction (if detected)
 *     - Summary paragraph
 *     - Flag count row (CRITICAL / SUSPECT / MINOR colored badges)
 *     - 5 Dimension scores with progress bars
 *     - Flagged clauses list (sorted by severity):
 *         - Severity badge + clause title
 *         - Description paragraph
 *         - Verbatim quote (italic, indented)
 *
 *   Footer (every page):
 *     - Left: "Generated by Clippy — clippy.legal | Page N"
 *     - Center: Legal disclaimer
 *     - Right: Analysis timestamp
 *
 * PAGE BREAK LOGIC
 * ----------------
 * checkPageBreak(neededMm) is called before rendering each block. If the
 * remaining space on the current page (PAGE_H - FOOTER_H - currentY) is less
 * than neededMm, a new page is added via addPage(). This prevents content from
 * being clipped at the page bottom.
 *
 * @param context - Export context (file name, timestamp, results)
 * @param downloadName - Optional filename for the downloaded PDF (without extension)
 */
export function downloadAsPDF(context: ExportContext, downloadName?: string): void {
  // A4 portrait, jsPDF default units = mm
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  // Page geometry constants (all in mm)
  const PAGE_W = 210;                        // A4 width
  const MARGIN = 14;                         // left/right margin
  const CONTENT_W = PAGE_W - MARGIN * 2;    // usable content width
  const PAGE_H = 297;                        // A4 height
  const FOOTER_H = 12;                       // reserved space for the footer (taller in v3.0.1 for disclaimer)
  const TOP_MARGIN = 14;                     // top margin for content pages

  // Y-position cursor — advances as we add content
  let y = TOP_MARGIN;

  // ---------------------------------------------------------------------------
  // Helper: add a new page and reset the cursor
  // The footer is stamped onto the page we're leaving, then a new page begins.
  // ---------------------------------------------------------------------------
  const addPage = () => {
    addFooter();
    doc.addPage();
    y = TOP_MARGIN;
  };

  // ---------------------------------------------------------------------------
  // Helper: check if we need a page break before rendering `neededMm` of content.
  // Adds a safety buffer of 4mm so content doesn't crowd the footer.
  // ---------------------------------------------------------------------------
  const checkPageBreak = (neededMm: number) => {
    if (y + neededMm > PAGE_H - FOOTER_H - 4) addPage();
  };

  // ---------------------------------------------------------------------------
  // Helper: render the footer on the current page.
  // Footer contains: attribution left | disclaimer center | timestamp right.
  // ---------------------------------------------------------------------------
  const addFooter = () => {
    const pageNum = doc.getNumberOfPages();

    // Attribution (left)
    doc.setFontSize(6.5);
    doc.setTextColor(150, 140, 120);
    doc.text(
      `Generated by Clippy — clippy.legal  |  Page ${pageNum}`,
      MARGIN,
      PAGE_H - 7
    );

    // Legal disclaimer (center) — slightly smaller
    doc.setFontSize(5.5);
    doc.setTextColor(180, 165, 140);
    doc.text(
      LEGAL_DISCLAIMER,
      PAGE_W / 2,
      PAGE_H - 4,
      { align: "center", maxWidth: CONTENT_W }
    );

    // Timestamp (right)
    doc.setFontSize(6.5);
    doc.setTextColor(150, 140, 120);
    doc.text(
      new Date(context.analyzedAt).toLocaleString(),
      PAGE_W - MARGIN,
      PAGE_H - 7,
      { align: "right" }
    );
  };

  // ---------------------------------------------------------------------------
  // Helper: render a horizontal rule at the current Y position.
  // Advances Y by 3mm after the rule.
  // ---------------------------------------------------------------------------
  const hr = (color = [220, 210, 190] as [number, number, number]) => {
    doc.setDrawColor(...color);
    doc.setLineWidth(0.25);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 3;
  };

  // ---------------------------------------------------------------------------
  // Cover / Header section (Page 1)
  // ---------------------------------------------------------------------------

  // Clippy logo mark — a rounded yellow rectangle with two navy circles (eyes)
  doc.setFillColor(245, 208, 0); // Clippy yellow (#F5D000)
  doc.roundedRect(MARGIN, y, 12, 18, 3, 3, "F");
  doc.setFillColor(26, 26, 46);  // Deep navy (#1a1a2e)
  doc.circle(MARGIN + 4, y + 8, 1.8, "F");  // left eye
  doc.circle(MARGIN + 8, y + 8, 1.8, "F");  // right eye

  // Title block
  doc.setFontSize(20);
  doc.setTextColor(26, 26, 46);
  doc.setFont("helvetica", "bold");
  doc.text("Clippy — Contract Analysis Report", MARGIN + 16, y + 7);

  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 95, 80);
  doc.text("clippy.legal — open-source AI contract analyzer · your contract analyst", MARGIN + 16, y + 13);
  y += 26;

  hr();

  // Contract file metadata block
  const metaLabel = (label: string, value: string, maxW: number = CONTENT_W - 26) => {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(26, 26, 46);
    doc.text(label, MARGIN, y);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(value, maxW);
    doc.text(lines, MARGIN + 24, y);
    y += lines.length * 5 + 1;
  };

  metaLabel("Contract:", context.fileName);
  metaLabel("Analyzed:", new Date(context.analyzedAt).toLocaleString());
  metaLabel("Models:", context.results.map(r => r.modelName).join(", "));

  if (context.promptTitles.length > 0) {
    metaLabel("Objectives:", context.promptTitles.join(", "));
  }

  y += 4;
  hr();
  y += 4;

  // ---------------------------------------------------------------------------
  // Per-model sections
  // ---------------------------------------------------------------------------

  for (const result of context.results) {
    checkPageBreak(30);

    // Model section header — warm cream background pill
    doc.setFillColor(248, 244, 232);
    doc.roundedRect(MARGIN, y - 1, CONTENT_W, 10, 2, 2, "F");
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(26, 26, 46);
    doc.text(result.modelName, MARGIN + 3, y + 6);

    // Trust score badge (top right)
    // Colour thresholds match the UI: green ≥75, yellow ≥50, orange ≥30, red <30
    const scoreColor: [number, number, number] =
      result.trustScore >= 75 ? [34, 197, 94]   :  // green
      result.trustScore >= 50 ? [234, 179, 8]   :  // yellow
      result.trustScore >= 30 ? [249, 115, 22]  :  // orange
                                [239, 68, 68];      // red
    doc.setFillColor(...scoreColor);
    doc.roundedRect(PAGE_W - MARGIN - 28, y, 26, 8, 2, 2, "F");
    doc.setFontSize(8.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text(`Score: ${result.trustScore}/100`, PAGE_W - MARGIN - 26, y + 5.5);
    y += 14;

    // Skip rendering detail for failed models
    if (result.status === "error") {
      doc.setFontSize(8.5);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(200, 60, 60);
      doc.text(`Analysis failed: ${result.error || "Unknown error"}`, MARGIN, y);
      y += 8;
      hr();
      continue;
    }

    // Jurisdiction
    if (result.jurisdiction && result.jurisdiction !== "Unknown") {
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100, 95, 80);
      doc.text(`Jurisdiction: ${result.jurisdiction}`, MARGIN, y);
      y += 5;
    }

    // Duration (right-aligned on the same row as jurisdiction, or on its own)
    if (result.durationMs) {
      doc.setFontSize(8);
      doc.setTextColor(150, 140, 120);
      doc.text(
        `Analysis time: ${(result.durationMs / 1000).toFixed(1)}s`,
        PAGE_W - MARGIN,
        y - 5,
        { align: "right" }
      );
    }

    // Summary
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(26, 26, 46);
    doc.text("Summary", MARGIN, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 45, 35);
    const summaryLines = doc.splitTextToSize(result.summary, CONTENT_W);
    checkPageBreak(summaryLines.length * 4 + 4);
    doc.text(summaryLines, MARGIN, y);
    y += summaryLines.length * 4 + 6;

    // Flag counts row (CRITICAL / SUSPECT / MINOR badges)
    checkPageBreak(12);
    const critCount  = result.flags.filter(f => f.severity === "CRITICAL").length;
    const suspCount  = result.flags.filter(f => f.severity === "SUSPECT").length;
    const minorCount = result.flags.filter(f => f.severity === "MINOR").length;

    const cells = [
      { label: "CRITICAL", count: critCount,  fill: [239, 68, 68]  as [number, number, number] },
      { label: "SUSPECT",  count: suspCount,  fill: [249, 115, 22] as [number, number, number] },
      { label: "MINOR",    count: minorCount, fill: [234, 179, 8]  as [number, number, number] },
    ];
    const cellW = 28;
    let cx = MARGIN;
    for (const cell of cells) {
      doc.setFillColor(...cell.fill);
      doc.roundedRect(cx, y, cellW, 8, 1.5, 1.5, "F");
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(255, 255, 255);
      doc.text(`${cell.count} ${cell.label}`, cx + cellW / 2, y + 5.5, { align: "center" });
      cx += cellW + 3;
    }
    y += 12;

    // Dimensions section
    if (result.dimensions.length > 0) {
      checkPageBreak(8 + result.dimensions.length * 7);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(26, 26, 46);
      doc.text("Dimensions", MARGIN, y);
      y += 5;

      for (const dim of result.dimensions) {
        checkPageBreak(9);

        // Dimension name + numeric score
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(50, 45, 35);
        doc.text(dim.name, MARGIN, y + 3);

        const dColor: [number, number, number] =
          dim.score >= 70 ? [34, 197, 94]  :  // green
          dim.score >= 45 ? [234, 179, 8]  :  // yellow
                            [239, 68, 68];     // red
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...dColor);
        doc.text(`${dim.score}/100`, MARGIN + 42, y + 3);

        // Progress bar track (grey)
        doc.setFillColor(230, 225, 210);
        doc.roundedRect(MARGIN + 58, y, CONTENT_W - 58, 4, 1, 1, "F");

        // Progress bar fill (coloured)
        doc.setFillColor(...dColor);
        doc.roundedRect(
          MARGIN + 58,
          y,
          (CONTENT_W - 58) * (dim.score / 100),
          4,
          1, 1, "F"
        );
        y += 7;
      }
      y += 2;
    }

    // Flagged clauses
    if (result.flags.length > 0) {
      checkPageBreak(12);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(26, 26, 46);
      doc.text(`Flagged Clauses (${result.flags.length})`, MARGIN, y);
      y += 5;

      // Sort by severity: CRITICAL first, then SUSPECT, then MINOR
      const sorted = [...result.flags].sort((a, b) => {
        const order: Record<string, number> = { CRITICAL: 0, SUSPECT: 1, MINOR: 2 };
        return (order[a.severity] ?? 3) - (order[b.severity] ?? 3);
      });

      for (const flag of sorted) {
        // Estimate height needed for this flag card
        const descLines  = doc.splitTextToSize(flag.description, CONTENT_W - 6);
        const quoteLines = flag.quote
          ? doc.splitTextToSize(`"${flag.quote}"`, CONTENT_W - 12)
          : [];
        const flagHeight =
          7 +
          descLines.length * 4 +
          (quoteLines.length ? quoteLines.length * 3.5 + 2 : 0) +
          3;
        checkPageBreak(flagHeight);

        // Flag card background — light tinted by severity
        const bgColor: [number, number, number] =
          flag.severity === "CRITICAL" ? [253, 242, 242] :
          flag.severity === "SUSPECT"  ? [255, 247, 237] :
                                         [254, 252, 232];
        doc.setFillColor(...bgColor);
        doc.roundedRect(MARGIN, y, CONTENT_W, flagHeight, 1.5, 1.5, "F");

        // Severity badge pill
        const badgeColor: [number, number, number] =
          flag.severity === "CRITICAL" ? [239, 68, 68]  :
          flag.severity === "SUSPECT"  ? [249, 115, 22] :
                                         [234, 179, 8];
        doc.setFillColor(...badgeColor);
        doc.roundedRect(MARGIN + 3, y + 2, 18, 4.5, 1, 1, "F");
        doc.setFontSize(6.5);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(255, 255, 255);
        doc.text(flag.severity, MARGIN + 12, y + 5.2, { align: "center" });

        // Flag title
        doc.setFontSize(8.5);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(26, 26, 46);
        doc.text(flag.title, MARGIN + 25, y + 5.2);

        // Description text
        doc.setFontSize(7.5);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(50, 45, 35);
        doc.text(descLines, MARGIN + 3, y + 10);
        let flagY = y + 10 + descLines.length * 4;

        // Verbatim quote (italic, slightly smaller, indented)
        if (quoteLines.length > 0) {
          doc.setFontSize(7);
          doc.setFont("helvetica", "italic");
          doc.setTextColor(100, 95, 80);
          doc.text(quoteLines, MARGIN + 8, flagY + 2);
          flagY += quoteLines.length * 3.5 + 2;
        }

        y += flagHeight + 2;
      }
    } else {
      // No flags — show a positive "all clear" message
      checkPageBreak(10);
      doc.setFontSize(8);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(34, 197, 94);
      doc.text("✓ No significant issues found — this contract appears fair.", MARGIN, y);
      y += 8;
    }

    y += 4;
    hr();
    y += 4;
  }

  // Stamp the footer on the final page
  addFooter();

  // Save the PDF — triggers the browser download dialog.
  // The filename is sanitised to remove characters that are invalid in filenames.
  const safeName = (downloadName || context.fileName.replace(/\.[^.]+$/, ""))
    .replace(/[^a-zA-Z0-9_\-. ]/g, "_")
    .slice(0, 80);
  doc.save(`${safeName}_clippy_report.pdf`);
}

// ---------------------------------------------------------------------------
// Markdown export
// ---------------------------------------------------------------------------

/**
 * Generates a Markdown report of the Clippy analysis results and triggers a download.
 *
 * OUTPUT FORMAT
 * -------------
 * The output is GitHub-compatible Markdown:
 *   - Headers (##, ###, ####)
 *   - Metadata table (Contract, Analyzed, Models, Objectives)
 *   - Per-model sections with trust score, jurisdiction, summary, flag counts
 *   - Dimensions table with ASCII progress bar (█░)
 *   - Flagged clauses as level-4 headers with descriptions and blockquoted quotes
 *   - Legal disclaimer footer
 *
 * The file is created as a Blob in memory and downloaded via a synthetic
 * <a> click. The Blob URL is revoked 2 seconds after click to prevent leaks.
 *
 * @param context - Export context (file name, timestamp, results)
 * @param downloadName - Optional filename for the downloaded Markdown file (without extension)
 */
export function downloadAsMarkdown(context: ExportContext, downloadName?: string): void {
  const lines: string[] = [];
  const date = new Date(context.analyzedAt).toLocaleString();

  // ---------------------------------------------------------------------------
  // Document header
  // ---------------------------------------------------------------------------
  lines.push("# 📎 Clippy — Contract Analysis Report");
  lines.push("");
  lines.push(`> Generated by [Clippy](https://clippy.legal) — open-source AI contract analyzer · *your contract analyst*`);
  lines.push("");

  // Metadata table
  lines.push("| Field | Value |");
  lines.push("| --- | --- |");
  lines.push(`| **Contract** | \`${context.fileName}\` |`);
  lines.push(`| **Analyzed** | ${date} |`);
  lines.push(`| **Models** | ${context.results.map(r => r.modelName).join(", ")} |`);
  if (context.promptTitles.length > 0) {
    lines.push(`| **Objectives** | ${context.promptTitles.join(", ")} |`);
  }
  lines.push("");
  lines.push("> ⚠ **Legal disclaimer:** AI-generated analysis. Not legal advice. Consult a qualified lawyer before acting on any finding.");
  lines.push("");
  lines.push("---");
  lines.push("");

  // ---------------------------------------------------------------------------
  // Per-model sections
  // ---------------------------------------------------------------------------
  for (const result of context.results) {
    lines.push(`## ${result.modelName}`);
    lines.push("");

    if (result.status === "error") {
      lines.push(`> ❌ **Analysis failed:** ${result.error || "Unknown error"}`);
      lines.push("");
      lines.push("---");
      lines.push("");
      continue;
    }

    // Trust score headline with colour-coded emoji
    const scoreEmoji =
      result.trustScore >= 75 ? "🟢" :
      result.trustScore >= 50 ? "🟡" :
      result.trustScore >= 30 ? "🟠" : "🔴";
    lines.push(`### ${scoreEmoji} Trust Score: **${result.trustScore}/100**`);
    lines.push("");

    if (result.jurisdiction && result.jurisdiction !== "Unknown") {
      lines.push(`📍 **Jurisdiction:** ${result.jurisdiction}`);
      lines.push("");
    }

    if (result.durationMs) {
      lines.push(`⏱ **Analysis time:** ${(result.durationMs / 1000).toFixed(1)}s`);
      lines.push("");
    }

    // Summary
    lines.push("### Summary");
    lines.push("");
    lines.push(result.summary);
    lines.push("");

    // Flag counts summary line
    const critCount  = result.flags.filter(f => f.severity === "CRITICAL").length;
    const suspCount  = result.flags.filter(f => f.severity === "SUSPECT").length;
    const minorCount = result.flags.filter(f => f.severity === "MINOR").length;
    lines.push(`🔴 **${critCount} CRITICAL** &nbsp; 🟠 **${suspCount} SUSPECT** &nbsp; 🟡 **${minorCount} MINOR**`);
    lines.push("");

    // Dimensions table with ASCII progress bar
    if (result.dimensions.length > 0) {
      lines.push("### Dimensions");
      lines.push("");
      lines.push("| Dimension | Score | Assessment | Note |");
      lines.push("| --- | --- | --- | --- |");
      for (const dim of result.dimensions) {
        // ASCII progress bar: 10 characters wide, filled proportionally
        const filled = Math.round(dim.score / 10);
        const bar = "█".repeat(filled) + "░".repeat(10 - filled);
        lines.push(`| ${dim.name} | **${dim.score}/100** \`${bar}\` | ${dim.label} | ${dim.note} |`);
      }
      lines.push("");
    }

    // Flagged clauses
    if (result.flags.length === 0) {
      lines.push("### ✅ No Issues Found");
      lines.push("");
      lines.push("No significant problematic clauses were identified. This contract appears fair.");
      lines.push("");
    } else {
      lines.push("### Flagged Clauses");
      lines.push("");

      // Sort by severity: CRITICAL first
      const sorted = [...result.flags].sort((a, b) => {
        const order: Record<string, number> = { CRITICAL: 0, SUSPECT: 1, MINOR: 2 };
        return (order[a.severity] ?? 3) - (order[b.severity] ?? 3);
      });

      for (const flag of sorted) {
        const emoji =
          flag.severity === "CRITICAL" ? "🔴" :
          flag.severity === "SUSPECT"  ? "🟠" : "🟡";
        lines.push(`#### ${emoji} ${flag.severity}: ${flag.title}`);
        lines.push("");
        lines.push(flag.description);
        if (flag.quote) {
          lines.push("");
          lines.push(`> *"${flag.quote}"*`);
        }
        lines.push("");
      }
    }

    lines.push("---");
    lines.push("");
  }

  // ---------------------------------------------------------------------------
  // Footer with legal disclaimer and attribution
  // ---------------------------------------------------------------------------
  lines.push("---");
  lines.push("");
  lines.push("*⚠ This report was generated by [Clippy](https://clippy.legal) — an open-source AI contract analyzer.*");
  lines.push("*Results are AI-generated and **do not constitute legal advice**. Consult a qualified lawyer before acting on any finding.*");
  lines.push("*Results may miss clauses, misinterpret context, or reflect outdated legal standards.*");
  lines.push("");
  lines.push(`*[View Clippy on GitHub](https://github.com/paulfxyz/clippy) · Report generated: ${date}*`);

  // ---------------------------------------------------------------------------
  // Build and trigger download via synthetic <a> click
  // ---------------------------------------------------------------------------
  const md = lines.join("\n");

  // Use UTF-8 charset to support non-Latin content (legal text often has
  // special characters, foreign names, currency symbols, etc.)
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  // Sanitise the filename: remove characters that are invalid in filenames
  // and limit to 80 characters to avoid OS filename length limits.
  const safeName = (downloadName || context.fileName.replace(/\.[^.]+$/, ""))
    .replace(/[^a-zA-Z0-9_\-. ]/g, "_")
    .slice(0, 80);

  const link = document.createElement("a");
  link.href = url;
  link.download = `${safeName}_clippy_report.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  // Revoke the object URL after a short delay to free memory.
  // The delay gives the browser time to start the download before we revoke.
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}
