/**
 * @file schema.ts
 * @description Shared TypeScript types used across the Clippy application.
 *
 * Clippy is entirely client-side in production — there is no server-side database.
 * These types define the shape of:
 *   - AI model analysis results (as they come back from OpenRouter)
 *   - The global application state machine
 *
 * All types are plain TypeScript interfaces / union types. No Drizzle schema,
 * no zod validators — we don't need them for a stateless client-side app.
 */

// ---------------------------------------------------------------------------
// Clause severity levels
// ---------------------------------------------------------------------------

/**
 * Severity of a flagged contract clause.
 *
 * - CRITICAL: The clause is clearly abusive, potentially illegal, or creates
 *   severe risk for the signing party (e.g. unlimited liability, auto-renewing
 *   terms with impossible exit windows, unilateral price changes).
 *
 * - SUSPECT: The clause is unusual, one-sided, or could be used against the
 *   signing party in a dispute. Worth reading and possibly negotiating.
 *
 * - MINOR: Common boilerplate that slightly favors the drafting party but is
 *   standard in the industry. Worth knowing, but usually not worth fighting over.
 */
export type Severity = "CRITICAL" | "SUSPECT" | "MINOR";

// ---------------------------------------------------------------------------
// Individual flagged clause
// ---------------------------------------------------------------------------

/**
 * A single problematic clause identified by an AI model.
 */
export interface ClauseFlag {
  /** Unique identifier for this flag (used as React key). Generated by the model. */
  id: string;

  /** Short title summarizing the issue (e.g. "Unlimited Liability Clause"). */
  title: string;

  /** Plain-language explanation of why this clause is problematic. */
  description: string;

  /** Severity classification. See Severity type above. */
  severity: Severity;

  /**
   * Verbatim short quote from the contract that triggered this flag.
   * Max ~100 chars. Used to help the user locate the clause in the original document.
   * Optional — some models may not include it reliably.
   */
  quote?: string;
}

// ---------------------------------------------------------------------------
// Analysis dimension
// ---------------------------------------------------------------------------

/**
 * A scored dimension of contract quality.
 *
 * Clippy uses 5 fixed dimensions:
 *   1. Transparency    — Is the contract clear and written in plain language?
 *   2. Balance         — Does the contract fairly represent both parties?
 *   3. Legal Compliance — Does it appear to comply with applicable law?
 *   4. Financial Risk  — What financial exposure does the signing party face?
 *   5. Exit Freedom    — How easy is it to terminate or exit the agreement?
 */
export interface Dimension {
  /** Dimension name (one of the 5 above). */
  name: string;

  /** Score from 0 (terrible) to 100 (excellent). */
  score: number;

  /** One-word assessment label (e.g. "Good", "Poor", "Risky"). */
  label: string;

  /** One-sentence contextual note explaining the score. */
  note: string;
}

// ---------------------------------------------------------------------------
// Per-model analysis result
// ---------------------------------------------------------------------------

/**
 * The complete result of one AI model analyzing a contract.
 *
 * Results start in "loading" status and transition to "done" or "error"
 * as the OpenRouter API call completes. All models run in parallel via
 * Promise.allSettled(), so results arrive independently.
 */
export interface ModelResult {
  /** OpenRouter model ID (e.g. "anthropic/claude-3.5-sonnet"). */
  modelId: string;

  /** Human-readable model name for display in the UI. */
  modelName: string;

  /**
   * Overall trust score for the contract, as assessed by this model.
   * 0 = maximally abusive, 100 = perfectly fair.
   * Clamped to [0, 100] in the API response handler.
   */
  trustScore: number;

  /** 2–3 sentence plain-language summary of the contract and its key risks. */
  summary: string;

  /** Array of flagged problematic clauses, sorted by severity in the UI. */
  flags: ClauseFlag[];

  /** Five dimension scores (Transparency, Balance, Legal Compliance, Financial Risk, Exit Freedom). */
  dimensions: Dimension[];

  /**
   * Detected legal jurisdiction (e.g. "England and Wales", "California, USA").
   * The model makes a best-effort guess — always verify with a real lawyer
   * for jurisdiction-specific advice.
   */
  jurisdiction?: string;

  /**
   * Lifecycle status of this result:
   * - "pending"  : Not yet started (reserved for future queued execution)
   * - "loading"  : API call in flight
   * - "done"     : Analysis complete, all fields populated
   * - "error"    : API call failed, `error` field contains the message
   */
  status: "pending" | "loading" | "done" | "error";

  /**
   * Error message if status === "error".
   * Includes the HTTP status and OpenRouter error description.
   */
  error?: string;
}

// ---------------------------------------------------------------------------
// Global application state
// ---------------------------------------------------------------------------

/**
 * The complete state of the Clippy application.
 *
 * This is managed as a single useState() object in Home.tsx.
 * The app progresses through steps: upload → config → analyzing → results.
 * The "New Analysis" button resets most state but preserves apiKey and selectedModels
 * for user convenience.
 */
export interface AnalysisState {
  /** The uploaded File object (needed for display of filename/size). Null before upload. */
  file: File | null;

  /**
   * Extracted plain text content of the uploaded file.
   * This is what gets sent to the AI models — not the raw binary.
   * Extracted client-side by fileParser.ts before any API call is made.
   */
  fileText: string;

  /**
   * The user's OpenRouter API key.
   * Held in React state only — never written to localStorage, cookies, or any
   * persistent storage. Wiped on page refresh. This is intentional for security.
   */
  apiKey: string;

  /**
   * Array of OpenRouter model IDs selected by the user.
   * Defaults to ["anthropic/claude-3.5-sonnet", "openai/gpt-4o"] on first load.
   */
  selectedModels: string[];

  /**
   * One ModelResult entry per selected model.
   * Populated when analysis starts, updated in place as results arrive.
   */
  results: ModelResult[];

  /**
   * Current step in the application flow.
   * Transitions: upload → config → analyzing → results
   * Reset: any step → upload (via "New Analysis" button)
   */
  step: "upload" | "config" | "analyzing" | "results";
}
